[package]
name = "backend_rust"
version = "0.1.0"
authors = ["Nicholas Miller <nicholas.anthony.miller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
