data:
    lexicon_fname: ./backend/data/lexemes.csv
    phoneme_fname: ./backend/data/phonemes.csv
    morpheme_fname: ./backend/data/morphemes.csv
    adposition_fname: ./backend/data/adpositions.csv
    sentences_fname: ./backend/data/sentences.csv
params:
    # sov | svo | vso | vos | osv | ovs
    word_order: sov

    # pre | post | morpheme
    adpositions: post

    # none | low | high
    noun_class: none

    # none | low | high
    noun_case: none

    # no | yes
    verb_copula: no

    # none | low | high
    verb_tense: none

    # none | low | high
    verb_person: none

    # none | low | high
    verb_number: none

    # none | low | high
    verb_gender: none

    # none | low | high
    verb_aspect: none

    # none | low | high
    verb_mood: high

    # none | low | high
    verb_attitudinal: high

    # none | low | high
    verb_evidential: high

    # none | low | high
    derivational: none

    # none | low | high
    verb_valence: none

    min_syl_per_word: 1
    max_syl_per_word: 2
    min_syl_per_morpheme: 1
    max_syl_per_morpheme: 1

    # none | low | high
    pronouns: low

    # none | low | high
    onomatopoeia: none

    # none | low | med | high
    phon_cons_difficulty: low

    # none | low | med | high
    phon_cons_number: low

    # none | low | med | high
    phon_vowel_difficulty: low

    # none | low | med | high
    phon_vowel_number: low

    # none | low | high
    phon_syl_cons: none

    # none | low | high
    phon_tone: high

    # no | yes
    phon_gemination: no

    # no | yes
    phon_vowel_length: yes

    # none | low | high
    phon_initial_clusters: none

    # none | low | high
    phon_final_clusters: none

    # none | low | high
    phon_diphthongs: none

    # none | low | high
    phon_non_egressive: yes

